# Generated by Django 5.1 on 2024-08-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_1', models.CharField(max_length=255)),
                ('category_2', models.CharField(max_length=255)),
                ('category_3', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('product_rating', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_rating', models.FloatField()),
                ('price_ratio', models.FloatField()),
                ('price_difference', models.FloatField()),
                ('product_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
