# Generated by Django 5.1 on 2024-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceUI', '0002_remove_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
