# Generated by Django 4.2.15 on 2024-08-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceUI', '0002_remove_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
