# Generated by Django 4.2.15 on 2024-08-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceUI', '0003_alter_product_category_1_alter_product_category_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
